import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen w-screen flex items-center justify-center bg-gray-800 text-white font-semibold text-xl">
          {children}
        </div>
      </body>
    </html>
  );
}
